### GENERAL SETTINGS ###

# Site settings
title: ©「哨兵」| Sentry Security
brand: Sentry Security
description: 哨兵安全实验室
baseurl: "" #important: start with /
url: "https://bin4xin.github.io"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
permalink: "/:categories/:year/:title/"
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

sass:
    sass_dir: assets/css
future: true
#google_verify: Lwh0NyQ1YAKRuLlXXkk0_QvgJpGLRQVA8xaoRn81Ysk

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "本站由哨兵安全实验室支持创办"

include: ['_pages']
