name: push-gh-pages

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run jekyll-build
      run: bundle exec jekyll build
    - name: Simple deploy with git
      uses: rdarida/simple-github-pages-deploy-action@v1
      with: # optional
        git-user: ${{ secrets.Git_USERNAME}}
        git-email: ${{ secrets.Git_EMAIL }}
        git-base-folder: '_site'
        commit-message: 'test'
        branch: 'gh-pages'
