name: sentrylab build sync and reload.

on:
  workflow_dispatch:
    inputs:
      note:
        description: "Test scenario tags"
        required: false
        default: "Let's go."
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 15 * * *'


env:
  github-Access: "https://github.com/Bin4xin"
  github-ReposAccess: "bin4xin.github.io"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      LSI: 'true'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Clone and copy files
      run: |
        git clone ${{ env.github-Access }}/${{ env.github-ReposAccess }}
        cd ${{ env.github-ReposAccess }}
        cp -R ../_posts/* _posts/
        echo "sentrylab.cn" > CNAME
        commitString=$(git rev-list HEAD --abbrev-commit --max-count=1)
        echo "commitString: $commitString" >> _config.yml
        sed -i "/^source/c source 'https://rubygems.org'" Gemfile

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Cache Ruby Bundler
      id: cache
      uses: actions/cache@v2
      env:
        CACHE_ID: 3
      with:
        path: /tmp/bundle
        key: ${{ runner.os }}-bundler-${{ env.CACHE_ID }}-${{ hashFiles('${{ env.github-ReposAccess }}/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-bundler-${{ env.CACHE_ID }}-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ env.github-ReposAccess }} && gem update --system 3.2.3 && bundle config set --local path 'vendor/bundle' && bundle install --jobs=4 --retry=3
        bundle exec jekyll build --trace
    - name: Simple deploy with git
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        BASE_BRANCH: 'main'
        BRANCH: 'gh-pages'
        FOLDER: '_site'
        commit-message: '<auto generate>:🚀sentinel home page build/deploy by github action.'